version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "maro114510"
    assignees:
      - "maro114510"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "maro114510"
    assignees:
      - "maro114510"
